---
- name: Install MacOS Packages
  hosts: localhost
  become: false
  vars:
    brew_cask_packages:
      - 1password
      - 1password-cli
      - caffeine
      - docker
      - google-chrome
      - intellij-idea
      - omnifocus
      - osxfuse
      - slack
      - spotify
    brew_packages:
      - autoconf
      - bash-completion
      - consul
      - docker-compose
      - gh
      - git
      - git-lfs
      - go
      - jq
      - mc
      - nmap
      - node
      - nomad
      - nvm
      - openssl
      - packer
      - pyenv
      - python
      - rbenv
      - ruby-build
      - ssh-copy-id
      - sshfs
      - terraform
      - terraform-inventory
      - terraform-provisioner-ansible
      - tmux
      - tree
      - vault
      - wget
    install_homebrew_if_missing: false
    upgrade_homebrew_packages: false

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: Installing Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing

  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists

    - name: Upgrading Homebrew Packages
      homebrew:
        upgrade_all: "{{ upgrade_homebrew_packages }}"
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: gitconfig
      template:
        src: files/gitconfig
        dest: /usr/local/etc/gitconfig
