---
- name: Install MacOS Packages
  hosts: localhost
  become: false
  vars:
    brew_cask_packages:
      - 1password
      - 1password-cli
      - caffeine
      - docker
      - google-chrome
      - google-cloud-sdk
      - intellij-idea
      - omnifocus
      - signal
      - slack
      - spotify
    brew_packages:
      - autoconf
      - awscli
      - bash-completion
      - consul
      - docker-compose
      - gh
      - git
      - git-lfs
      - go
      - jq
      - kubectl
      - mc
      - nmap
      - node
      - nomad
      - nvm
      - openssl
      - packer
      - pyenv
      - python
      - rbenv
      - ruby-build
      - ssh-copy-id
      - terraform
      - terraform-inventory
      - tmux
      - tree
      - vault
      - wget
    install_homebrew_if_missing: false
    upgrade_homebrew_packages: false

  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true

    - name: Upgrading Homebrew Packages
      homebrew:
        upgrade_all: "{{ upgrade_homebrew_packages }}"
      register: result
      until: result is successful

    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
      register: result
      until: result is successful

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      register: result
      until: result is successful

    - name: gitconfig
      template:
        src: files/gitconfig
        dest: /opt/homebrew/etc/gitconfig
